name: Java APP CI/CD Pipeline

on: push


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
                
            - name: Install Dependencies
              run: npm install
              working-directory: ./app/

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@main
              env:
                SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}